# Generated by Django 5.0 on 2023-12-22 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0003_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ISBN',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
