# Generated by Django 5.0 on 2023-12-22 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0004_product_isbn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='ISBN',
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='product',
            name='isbn',
            field=models.CharField(max_length=17, null=True),
        ),
    ]
