# Generated by Django 5.0 on 2023-12-23 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0005_alter_orderitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='return_data',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
