# Generated by Django 5.0 on 2023-12-22 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0005_remove_product_isbn_alter_product_id_product_isbn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='isbn',
            field=models.CharField(max_length=17, null=True, unique=True),
        ),
    ]
