# Generated by Django 5.0 on 2023-12-24 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0007_product_isbn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='isbn',
            field=models.CharField(blank=True, max_length=17, null=True, unique=True),
        ),
    ]
